################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Unikom
      Name: UnikomMSP
      ID: UnikomMSP
      MSPDir: crypto-config/peerOrganizations/unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('UnikomMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('UnikomMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('UnikomMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('UnikomMSP.member')"

      AnchorPeers:

    - &WakilRektor
      Name: WakilRektorMSP
      ID: WakilRektorMSP
      MSPDir: crypto-config/peerOrganizations/wr.unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('WakilRektorMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('WakilRektorMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('WakilRektorMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('WakilRektorMSP.member')"

      AnchorPeers:
          - Host: peer0.wr.unikom.ac.id
            Port: 7041

    - &Direktorat
      Name: DirektoratMSP
      ID: DirektoratMSP
      MSPDir: crypto-config/peerOrganizations/direktorat.unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('DirektoratMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('DirektoratMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('DirektoratMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('DirektoratMSP.member')"

      AnchorPeers:
          - Host: peer0.direktorat.unikom.ac.id
            Port: 7061

          - Host: peer1.direktorat.unikom.ac.id
            Port: 7062

    - &ProgramStudi
      Name: ProgramStudiMSP
      ID: ProgramStudiMSP
      MSPDir: crypto-config/peerOrganizations/prodi.unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('ProgramStudiMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('ProgramStudiMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('ProgramStudiMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('ProgramStudiMSP.member')"

      AnchorPeers:
          - Host: peer0.prodi.unikom.ac.id
            Port: 7081

    - &PIC
      Name: PICMSP
      ID: PICMSP
      MSPDir: crypto-config/peerOrganizations/pic.unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PICMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('PICMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('PICMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('PICMSP.member')"

      AnchorPeers:
          - Host: peer0.pic.unikom.ac.id
            Port: 7101

    - &Mahasiswa
      Name: MahasiswaMSP
      ID: MahasiswaMSP
      MSPDir: crypto-config/peerOrganizations/mahasiswa.unikom.ac.id/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('MahasiswaMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('MahasiswaMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('MahasiswaMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('MahasiswaMSP.member')"

      AnchorPeers:
          - Host: peer0.mahasiswa.unikom.ac.id
            Port: 7121

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &UnikomDefaults
    OrdererType: solo
    Addresses:
        - orderer0.unikom.unikom.ac.id:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group unikom #
    UnikomGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *UnikomDefaults
            Organizations:
                - *Unikom
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Unikom
                    - *WakilRektor
                    - *Direktorat
                    - *ProgramStudi
                    - *PIC
                    - *Mahasiswa

    # Profile used to create channeltx for pendaftaran #
    Pendaftaran:
        <<: *ChannelDefaults
        Orderer:
            <<: *UnikomDefaults
            Organizations:
                - *Unikom
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *WakilRektor
                    - *PIC
                    - *Mahasiswa
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *WakilRektor
                - *PIC
                - *Mahasiswa

    # Profile used to create channeltx for nilai #
    Nilai:
        <<: *ChannelDefaults
        Orderer:
            <<: *UnikomDefaults
            Organizations:
                - *Unikom
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *WakilRektor
                    - *Direktorat
                    - *ProgramStudi
                    - *PIC
                    - *Mahasiswa
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *WakilRektor
                - *Direktorat
                - *ProgramStudi
                - *PIC
                - *Mahasiswa
